CREATE DATABASE IF NOT EXISTS `coupon` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE coupon;

CREATE TABLE IF NOT EXISTS `coupon` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uuid` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL DEFAULT '',
  `img` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`time`),
  UNIQUE KEY (`uuid`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `telephone` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `coupon_id` INT(10) NOT NULL,
  `tel` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`time`)
) ENGINE = InnoDB;
